version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "nandenjin"
    reviewers:
      - "nandenjin"
    labels:
      - "dependencies"
      - "automerge"
