# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [dev, "renovate/*"]
  pull_request:
    branches: [dev]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || !startsWith(github.head_ref, 'renovate/')

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn run lint
